# Generated by Django 2.2 on 2022-07-06 06:29

from django.db import migrations, models
import tweetme2.yandex_s3_storage


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=tweetme2.yandex_s3_storage.ClientDocsStorage(), upload_to='tweetme/profile_pic'),
        ),
    ]
