# Generated by Django 2.2 on 2022-07-06 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_auto_20220706_0629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created']},
        ),
    ]
